version: "3.9"

services:

  currencyconverter:
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: 
      always
    image: 
      postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpwd"
      POSTGRES_DB: "postgres"
    volumes:
      - ./scripts/pg:/docker-entrypoint-initdb.d/
#   test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]    
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]   
      timeout: 60s
      interval: 10s
      retries: 10
    container_name: postgresdb
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend: 